#ifndef APPPCH_H
#define APPPCH_H
#include <iostream>
#include "EASTL/vector.h"
#include "EASTL/string.h"
#include "EASTL/array.h"
#include "EASTL/memory.h"
#include "EASTL/string_view.h"
#include "EASTL/functional.h"
#include "EASTL/shared_ptr.h"
#include "EASTL/weak_ptr.h"
#include "EASTL/safe_ptr.h"
#include "EASTL/unique_ptr.h"
#include "EASTL/intrusive_ptr.h"
#include "EASTL/linked_ptr.h"
#include "EASTL/scoped_ptr.h"
#include "EASTL/shared_array.h"
#include "EASTL/scoped_array.h"
#include "EASTL/linked_array.h"
#include "EASTL/algorithm.h"
#include "EASTL/iterator.h"
#include "EASTL/utility.h"
#include <iostream>
#include <memory>
#include <vector>
#include <functional>
#include <utility>
#include <algorithm>
#include <string>
#include <string_view>
#include <array>
#include "AppConfig.h"
#include "Core/Logger.h"
#endif